# PERSONAL CONFIG FILE

# CLIENT CONFIG
FONT="White Rabbit"#"NovaMono"#'Speculum'
FONTSIZE=18
WIDTH=85
HEIGHT=45
WINDOWSIZE="1250x910"
HOST="localhost"
PORT=12345
NAME="Aamstrang Karpov"
REFRESHINTERVAL=0 # Leave very low

# SERVER CONFIG
SERVERNAME="localhost"
SERVERPORT=12345
MIDINAME='Midi Through Port-0'
SLEEP_SCHEDULER=0.3
